[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
flap = "5LeA7rgKeS5Mkga4Eju2pom9qbqs7WwUdfBs9zRvLYov"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
